development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: terminal_development
  pool: 5
  username: root
  password:
  socket: /var/lib/mysql/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: terminal_test
  pool: 5
  username: root
  password:
  socket: /var/lib/mysql/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: terminal
  pool: 5
  username: root
  password:
  socket: /var/lib/mysql/mysql.sock